#!/usr/bin/env bash
# Discover or create everything the bundle cannot guess, then write the values
# out as bundle variable overrides.
#
# Three ids in this demo are generated by the platform at creation time and are
# different in every workspace: the SQL warehouse id, the Lakebase database
# resource path, and the compute endpoint uid used for billing attribution.
# Committing them is what makes a demo un-runnable by anyone else, so this script
# resolves them at run time and writes `.crfs.vars`, which is gitignored and which
# setup.sh turns into `--var` flags.
#
# Idempotent: run it as often as you like. It creates only what is missing.
#
#   scripts/bootstrap.sh --profile <PROFILE> [--catalog C] [--schema S]
#                        [--store NAME] [--capacity CU_1] [--warehouse ID]
#                        [--no-create]
set -uo pipefail

PROFILE=""
CATALOG=""
SCHEMA="crunchyroll_demo"
STORE="crunchyroll-online-store"
CAPACITY="CU_1"
WAREHOUSE=""
BRANCH="production"
ENDPOINT="primary"
CREATE=1
OUT=".crfs.vars"

while [ $# -gt 0 ]; do
  case "$1" in
    --profile)    PROFILE="$2"; shift 2 ;;
    --catalog)    CATALOG="$2"; shift 2 ;;
    --schema)     SCHEMA="$2"; shift 2 ;;
    --store)      STORE="$2"; shift 2 ;;
    --capacity)   CAPACITY="$2"; shift 2 ;;
    --warehouse)  WAREHOUSE="$2"; shift 2 ;;
    --out)        OUT="$2"; shift 2 ;;
    --no-create)  CREATE=0; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

DB=$(command -v databricks || echo /opt/homebrew/bin/databricks)
ok()   { printf '  \033[32mok\033[0m    %s\n' "$1"; }
made() { printf '  \033[36mnew\033[0m   %s\n' "$1"; }
bad()  { printf '  \033[31mFAIL\033[0m  %s\n' "$1"; }
warn() { printf '  \033[33mwarn\033[0m  %s\n' "$1"; }
die()  { bad "$1"; exit 1; }

if [ -z "$PROFILE" ]; then
  echo "A profile is required. Available profiles in ~/.databrickscfg:" >&2
  "$DB" auth profiles -o json 2>/dev/null | python3 -c '
import json, sys
for p in json.load(sys.stdin).get("profiles", []):
    print("  %-32s %s" % (p.get("name"), p.get("host")), file=sys.stderr)
' || true
  echo >&2
  echo "  scripts/bootstrap.sh --profile <NAME>" >&2
  exit 2
fi

echo "bootstrap  profile=$PROFILE"
echo

# ------------------------------------------------------------------ CLI and auth
ver=$("$DB" --version 2>/dev/null | tr -d 'v' | awk '{print $NF}')
[ -n "$ver" ] || die "databricks CLI not found on PATH"
python3 - "$ver" <<'PY' || die "databricks CLI $ver is too old; this bundle needs >= 1.14.0"
import sys
parts = [int(x) for x in sys.argv[1].split(".")[:3] if x.isdigit()]
sys.exit(0 if parts >= [1, 14] else 1)
PY
ok "databricks CLI $ver"

USER_JSON=$("$DB" current-user me --profile "$PROFILE" -o json 2>/dev/null) \
  || die "cannot authenticate with profile $PROFILE (try: databricks auth login --profile $PROFILE)"
USER_NAME=$(printf '%s' "$USER_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["userName"])')
HOST=$("$DB" auth env --profile "$PROFILE" 2>/dev/null \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["env"]["DATABRICKS_HOST"])' 2>/dev/null)
ok "authenticated as $USER_NAME"
[ -n "$HOST" ] && ok "workspace $HOST"

# ------------------------------------------------------------------------ catalog
# Default to the first catalog the caller can actually create a schema in, rather
# than to a name from another workspace. A wrong catalog fails 40 minutes into the
# pipeline; resolving it here fails in two seconds.
if [ -z "$CATALOG" ]; then
  CATALOG=$("$DB" catalogs list --profile "$PROFILE" -o json 2>/dev/null | python3 -c '
import json, sys
rows = json.load(sys.stdin)
prefer = [c for c in rows if c.get("catalog_type") == "MANAGED_CATALOG"
          and c.get("name") not in ("system", "samples", "__databricks_internal")]
print((prefer or rows)[0]["name"] if (prefer or rows) else "")
' 2>/dev/null)
  [ -n "$CATALOG" ] || die "no usable Unity Catalog found; pass --catalog"
  warn "no --catalog given, using $CATALOG"
fi

if "$DB" schemas get "$CATALOG.$SCHEMA" --profile "$PROFILE" >/dev/null 2>&1; then
  ok "schema $CATALOG.$SCHEMA exists"
elif [ "$CREATE" = "1" ]; then
  "$DB" schemas create "$SCHEMA" "$CATALOG" \
    --comment "Crunchyroll shared feature store demo: horizontal and vertical ranking" \
    --profile "$PROFILE" >/dev/null 2>&1 \
    && made "created schema $CATALOG.$SCHEMA" \
    || die "cannot create schema $CATALOG.$SCHEMA - check CREATE SCHEMA on $CATALOG"
else
  warn "schema $CATALOG.$SCHEMA missing (--no-create)"
fi

# ---------------------------------------------------------------------- warehouse
# Needed by the dashboard and the app. Prefer a running serverless warehouse so
# the first dashboard load is not a two-minute cold start.
if [ -z "$WAREHOUSE" ]; then
  WAREHOUSE=$("$DB" warehouses list --profile "$PROFILE" -o json 2>/dev/null | python3 -c '
import json, sys
rows = [w for w in json.load(sys.stdin) if w.get("enable_serverless_compute")]
rows.sort(key=lambda w: (w.get("state") != "RUNNING", w.get("name", "")))
print(rows[0]["id"] if rows else "")
' 2>/dev/null)
fi
if [ -n "$WAREHOUSE" ]; then
  wh_state=$("$DB" warehouses get "$WAREHOUSE" --profile "$PROFILE" -o json 2>/dev/null \
    | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["name"], d["state"])' 2>/dev/null)
  ok "serverless warehouse $WAREHOUSE ($wh_state)"
elif [ "$CREATE" = "1" ]; then
  WAREHOUSE=$("$DB" warehouses create --json '{
      "name": "crfs-demo-warehouse", "cluster_size": "2X-Small", "max_num_clusters": 1,
      "auto_stop_mins": 10, "enable_serverless_compute": true, "warehouse_type": "PRO"
    }' --profile "$PROFILE" -o json 2>/dev/null \
    | python3 -c 'import json,sys; print(json.load(sys.stdin).get("id",""))' 2>/dev/null)
  [ -n "$WAREHOUSE" ] && made "created serverless warehouse $WAREHOUSE" \
    || die "no serverless SQL warehouse and could not create one"
else
  die "no serverless SQL warehouse found; pass --warehouse"
fi

# ------------------------------------------------------- online feature store
# The feature store must own this project. Creating the Lakebase project by hand
# (or declaring it in the bundle) produces a project the feature store will not
# resolve at serving time, and `bundle destroy` could then delete the online store
# out from under the published tables.
store_json=$("$DB" feature-store get-online-store "$STORE" --profile "$PROFILE" -o json 2>/dev/null)
if [ -n "$store_json" ]; then
  printf '%s' "$store_json" | python3 -c '
import json, sys
d = json.load(sys.stdin)
print("  \033[32mok\033[0m    online store %s: state=%s capacity=%s replicas=%s"
      % (d["name"], d["state"], d["capacity"], d.get("read_replica_count", 0)))
'
elif [ "$CREATE" = "1" ]; then
  echo "  creating online store $STORE at $CAPACITY (this takes a few minutes)"
  "$DB" feature-store create-online-store "$STORE" "$CAPACITY" --profile "$PROFILE" -o json \
    >/dev/null 2>&1 || die "could not create online store $STORE"
  for _ in $(seq 1 60); do
    state=$("$DB" feature-store get-online-store "$STORE" --profile "$PROFILE" -o json 2>/dev/null \
      | python3 -c 'import json,sys; print(json.load(sys.stdin).get("state",""))' 2>/dev/null)
    [ "$state" = "AVAILABLE" ] && break
    sleep 10
  done
  [ "$state" = "AVAILABLE" ] && made "online store $STORE is AVAILABLE" \
    || die "online store $STORE did not reach AVAILABLE (last state: ${state:-unknown})"
else
  warn "online store $STORE missing (--no-create)"
fi

PROJECT="$STORE"
EP_PATH="projects/$PROJECT/branches/$BRANCH/endpoints/$ENDPOINT"

# ------------------------------------------------- generated ids: the whole point
ep_json=$("$DB" postgres get-endpoint "$EP_PATH" --profile "$PROFILE" -o json 2>/dev/null)
EP_UID=""
if [ -n "$ep_json" ]; then
  EP_UID=$(printf '%s' "$ep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("uid",""))')
  printf '%s' "$ep_json" | python3 -c '
import json, sys
s = json.load(sys.stdin).get("status", {})
print("  \033[32mok\033[0m    lakebase endpoint %s: %s, %s-%s CU"
      % (s.get("endpoint_id"), s.get("current_state"),
         s.get("autoscaling_limit_min_cu"), s.get("autoscaling_limit_max_cu")))
'
else
  warn "lakebase endpoint $EP_PATH not resolvable yet"
fi

DB_RESOURCE=$("$DB" postgres list-databases "projects/$PROJECT/branches/$BRANCH" \
  --profile "$PROFILE" -o json 2>/dev/null | python3 -c "
import json, sys
want = '$CATALOG'
rows = json.load(sys.stdin) or []
for d in rows:
    if (d.get('status') or {}).get('postgres_database') == want:
        print(d['name']); break
" 2>/dev/null)
if [ -n "$DB_RESOURCE" ]; then
  ok "lakebase database resource $DB_RESOURCE"
else
  # It only appears once a feature table has been published into the catalog, so
  # on a first run this is expected. setup.sh re-runs bootstrap after the
  # pipeline, and the app deploy is what actually needs it.
  warn "lakebase database resource for $CATALOG not present yet (appears after the first publish)"
fi

# ------------------------------------------------------------------ LLM endpoint
LLM=$("$DB" serving-endpoints list --profile "$PROFILE" -o json 2>/dev/null | python3 -c '
import json, sys
names = [e["name"] for e in json.load(sys.stdin)]
for want in ("databricks-claude-sonnet-4-5", "databricks-claude-3-7-sonnet"):
    if want in names:
        print(want); raise SystemExit
for n in names:
    if n.startswith("databricks-claude"):
        print(n); raise SystemExit
print("")
' 2>/dev/null)
[ -n "$LLM" ] && ok "chat model $LLM (explainer agent)" \
  || warn "no databricks-hosted Claude endpoint found; the agent notebook will need var.llm_endpoint"

# --------------------------------------------------------------------- write vars
{
  echo "# Generated by scripts/bootstrap.sh -- do not commit, do not hand-edit."
  echo "# Values the platform generates per workspace; setup.sh passes them as --var."
  echo "CRFS_PROFILE=$PROFILE"
  echo "catalog=$CATALOG"
  echo "schema=$SCHEMA"
  echo "online_store=$STORE"
  echo "online_capacity=$CAPACITY"
  echo "lakebase_project=$PROJECT"
  echo "lakebase_branch=$BRANCH"
  echo "lakebase_endpoint=$ENDPOINT"
  echo "warehouse_id=$WAREHOUSE"
  echo "notification_email=$USER_NAME"
  [ -n "$LLM" ] && echo "llm_endpoint=$LLM"
  [ -n "$DB_RESOURCE" ] && echo "lakebase_db_resource=$DB_RESOURCE"
  [ -n "$EP_UID" ] && echo "# lakebase_endpoint_uid (billing filter, not a bundle var): $EP_UID"
} > "$OUT"

echo
ok "wrote $OUT"
sed 's/^/        /' "$OUT"
